const pokemons = [
  {
    id: '1',
    name: 'Pikachu',
    evolution: 'Raichu',
    species: 'Mouse Pokemon',
    logo: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/025.png',
    type: 'Electric',
  },
  {
    id: '2',
    name: 'Mew',
    evolution: 'Mewtwo',
    species: 'New Species Pokémon',
    logo: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/151.png',
    type: 'Psychic',
  },
  {
    id: '3',
    name: 'Charmander',
    evolution: 'Charmeleon',
    species: 'Lizard Pokémon',
    logo: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/004.png',
    type: 'Fire',
  },
  {
    id: '4',
    name: 'Bulbasaur',
    evolution: 'Ivysaur',
    species: 'Seed Pokémon',
    logo: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/001.png',
    type: 'Plant',
  },
  {
    id: '5',
    name: 'Squirtle',
    evolution: 'Wartortle, Blastoise',
    species: 'Tiny Turtle Pokémon',
    logo: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/007.png',
    type: 'Water',
  },
  {
    id: '6',
    name: 'Pidgeot',
    evolution: 'Pidgeot',
    species: 'Bird Pokémon',
    logo: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/017.png',
    type: 'Air',
  },
  {
    id: '7',
    name: 'Chikorita',
    evolution: 'Bayleaf, Meganium',
    species: 'Leaf Pokémon',
    logo: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/152.png',
    type: 'Plant',
  },
  {
    id: '8',
    name: 'Psyduck',
    evolution: 'Golduck',
    species: 'Duck Pokémon',
    logo: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/054.png',
    type: 'Water',
  },
  {
    id: '9',
    name: 'Vulpix',
    evolution: 'Ninetales',
    species: 'Fox Pokémon',
    logo: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/037.png',
    type: 'Fire',
  },
];

export default pokemons;
